[build]
  command = "npm run build"
  functions = "lambda/"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[dev]
  command = "npm start"
  functions = "lambda/"